### ISSUE TITLE
Validation of datalink URLs

### ISSUE THREAD

**Issue by hannako** [datagovuk/publish_data_beta#121]
- check datalinks have valid URLs in the dataset creation flow

**Comment by rossjones** [comment]
Can re-use the code in https://github.com/datagovuk/publish_data_beta/blob/master/lib/util/linkchecker.rb

**Comment by govuklaurence** [comment]
Toby Retallick [10:18] 
Hey @here -

As promised, I brainstormed a list of things we might want to check regarding the data link urls. Please let me know your thoughts. @louisepetre  can you let me know if you want new error messages to appear alongside these?

1. Url not present (Current error message: 'Please enter a valid url')
2. Url is empty string
3. Url does not have a valid domain
4. Url doesnot have a valid path
5.Url points to a dodgy website?
6. Javascript has been injected into the url (edited)


Laurence Smith 
[10:19] 
with new TLDs i think #3 may not be doable


[10:19] 
that’ll have to wait for the actual check


Ross Jones 
[10:19] 
It should check all those things, but I think you get pretty much the same error message for each.  There was some different content (so for instance, if you don't start with http(s) then it should give a different warning.


Toby Retallick [10:20] 
- yes forgot to add check for http https


Laurence Smith 
[10:20] 
#5 we will have to deal with at some point but rn let’s just stick in a blacklist


[10:21] 
#6 i’m curious how that’s possible


Ross Jones 
[10:21] 
I think that may be enough for now.  When eventually we (you) do file upload, there'll need to be teardown containers that can do virus/trojan checks on them, so can make use of that then.


Laurence Smith 
[10:21] 
^


Jonathan Nichols [10:21] 
Please can we make sure this detail makes it onto a ticket? Remember Slack is very transient (only a day or so of history..gulp)
