### ISSUE TITLE
Application hangs if no link specified

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_beta#160]
Steps:
- create a daily dataset
- on the 'add a link to your dataset', just click 'Save and continue'
- wait forever

**Comment by rossjones** [comment]
Closed by mistake

**Comment by rossjones** [comment]
When I do this, it shows me the correct validation message. However if I just click submit again I get ```No route matches [PUT] "/datasets/sdfsdf/files"

Rails.root: /Users/rossjones/Projects/beta/publish_data_beta```
