### ISSUE TITLE
Install Publish/Find Beta on PaaS

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_beta#233]

**Comment by maxf** [comment]
Seems PaaS postgres service doesn't support some extensions, eg: `PG::InsufficientPrivilege: ERROR:  permission denied to create extension "uuid-ossp"`. Currently waiting for them to find out if there's a way to make it work

**Comment by rossjones** [comment]
We've removed the dependency and now create uuids on before_save (if it isn't already set).  Should be good to go for moving to PaaS.

**Comment by maxf** [comment]
There are still issues with static assets not showing.
