### ISSUE TITLE
Use gov-uk lint

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/publish_data_beta#272]
https://rubygems.org/gems/govuk-lint

And enable it on codeclimate if possible

**Comment by rossjones** [comment]
Installation is at https://github.com/datagovuk/publish_data_beta/pull/271 

Once merged, will send a PR with fixes to the codebase (using the magical -a) and make sure tests pass before adding to code climate...

**Comment by hannako** [comment]
Add git commit hook

**Comment by rossjones** [comment]
To add a git pre-commit hook...

```
touch .git/hooks/pre-commit
chmod u+x .git/hooks/pre-commit
```

Add the following to that .git/hooks/pre-commit file.

```
#!/bin/sh

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "Running Linters:"

# Run tslint and get the output and return code
govuklint=$(bundle exec govuk-lint-ruby lib app spec)
ret_code=$?

if [ $ret_code != 0 ]; then
    echo "$govuklint\n"
    printf "\n${RED}govuk lint failed${NC}\n\n"
    pass=false
else
    printf "${GREEN}govuklint passed.${NC}\n"
fi

if $pass; then
    exit 0
fi

exit 1
```

This will stop you creating a commit if the linter fails.  Don't do this until we have removed all of the linting errors.
