### ISSUE TITLE
Validation rules + content

### ISSUE THREAD

**Issue by rossjones** [datagovuk/publish_data_beta#32]
Document validation rules from Alpha so we have a starting point.  Validation is different when creating a dataset (for draft) than for publishing, which is much stricter.  There are rules around when we can publish without a datafile, or with broken datafiles and we should make sure these are also documented.

**Comment by rossjones** [comment]
Also, we should make sure we use the content from Alpha for error messages rather than any rails defaults.

**Comment by govuklaurence** [comment]
Agreed. We can definitely override :)
