### ISSUE TITLE
Title field description should say 100 char limit (not 65)

### ISSUE THREAD

**Issue by nicholsj** [datagovuk/publish_data_beta#33]
From a beta Publisher:

The field description says titles should be less than 65 characters but the field limit is 100, it's a bit confusing.

**Comment by rossjones** [comment]
We should check, but I think the 100 is bytes, rather than chars.  Some utf8 chars use more than one byte...

**Comment by govuklaurence** [comment]
Postgres doesn't use a 1 byte primitive for char fortunately (so far as I can tell). So changed the text on beta.

**Comment by rossjones** [comment]
Ah, it should be 65 (according to the content) as that's a reasonable max-length for the title.

**Comment by govuklaurence** [comment]
Ah. I'll change it back.

**Comment by govuklaurence** [comment]
Changed back in `laurence/dataset-flow` branch
