### ISSUE TITLE
Make application text easy to translate

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_beta#79]
internationalisation, localisation, you name it. http://guides.rubyonrails.org/i18n.html

**Comment by rossjones** [comment]
Worth noting the default i18n is not gettext based, and will result in us putting content in yaml files and referencing like ```<% t '.title'  %>``` in the templates :( 

Maybe we could look at something like https://github.com/grosser/gettext_i18n_rails ?

**Comment by govuklaurence** [comment]
Refer to #231
