### ISSUE TITLE
Use slugs instead of IDs for datasets

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/publish_data_beta#80]

**Comment by rossjones** [comment]
We may need to support uuid && slug if we want to keep existing links (from legacy) working.

**Comment by rossjones** [comment]
Because of all the issues around slugs (checking for existing use, has the title changed etc) perhaps it makes more sense to only set the name field as the dataset is published?

**Comment by govuklaurence** [comment]
https://github.com/norman/friendly_id
