### ISSUE TITLE
radio button styles only picked up if you land on the page after pressing skip on the previous page

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/publish_data_beta#87]
Fallout of #86

**Comment by rossjones** [comment]
Had a look, the correct styles are flashing up for me, then reverting to non-styled version.

I also think the ```<div class="form-group<%= " error" if dataset.errors.include?(field[:name])%>" id="<%= field[:name] %>-form-group">``` might need moving up a level as it is wrapping every field at the moment.
